[package]
name = "rgb-lib"
version = "0.2.2"
authors = [
	"Zoe Faltibà <zoefaltiba@gmail.com>",
	"Nicola Busanello <nicola.busanello@gmail.com>",
]
edition = "2021"
rust-version = "1.67"
repository = "https://github.com/RGB-Tools/rgb-lib"
homepage = "https://github.com/RGB-Tools/rgb-lib"
license = "MIT"
description = "RGB wallet library"
exclude = ["migration"]

[workspace]
members = [".", "migration"]

[dependencies]
base64 = "0.21.0"
bdk = { version = "0.29", features = ["electrum", "keys-bip39"] }
bitcoin = "0.30.1"
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
copy_dir = "0.1.3"
electrum-client = "0.17.0"
futures = "0.3"
hex = "0.4.3"
rand = "0.8.5"
rgb-lib-migration = { path = "migration", version = "0.2.0" }
reqwest = { version = "0.11", default-features = false, features = [
	"blocking",
	"json",
	"multipart",
	"native-tls",
] }
scrypt = "0.11.0"
sea-orm = { version = "=0.12.14", features = [
	"sqlx-sqlite",
	"runtime-async-std-native-tls",
	"macros",
] }
sea-query = "=0.30.7"
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0", features = ["preserve_order"] }
slog = "2.7.0"
slog-async = "2.8.0"
slog-term = "2.9.0"
tempfile = "3.8.0"
thiserror = "1.0"
time = "0.3.28"
tree_magic = "0.2.3"
typenum = "1.16.0"
walkdir = "2.3.3"
zip = { version = "0.6.6", default-features = false, features = ["zstd"] }

# RGB-related deps
amplify = "=4.5.0"
amplify_num = "=0.5.1"  # temporary dependency pin
bp-core = "=0.10.11"
commit_verify = "=0.10.6"
rgb-contracts = "=0.10.2"
rgb-schemata = "=0.10.1"
rgb-std = "=0.10.9"
rgb-wallet = "=0.10.9"
rgb_core = { package = "rgb-core", version = "=0.10.8" }
strict_encoding = "=2.6.2"
strict_types = "=1.6.3"

[dev-dependencies]
dircmp = "0.2.0"
electrum-client = "0.17.0"
lazy_static = "1.4.0"
once_cell = "1.18.0"
regex = "1.9.5"
serial_test = "2.0.0"
tempfile = "3.8"
