[package]
name = "rgb-lib"
version = "0.2.2"
authors = [
    "Zoe Faltibà <zoefaltiba@gmail.com>",
    "Nicola Busanello <nicola.busanello@gmail.com>",
]
edition = "2021"
rust-version = "1.67"
repository = "https://github.com/RGB-Tools/rgb-lib"
homepage = "https://github.com/RGB-Tools/rgb-lib"
license = "MIT"
description = "RGB wallet library"
exclude = ["migration"]

[workspace]
members = [".", "migration"]

[dependencies]
base64 = { version = "0.21.0", default-features = false }
bdk = { version = "0.29", default-features = false, features = [
    "electrum",
    "key-value-db",
    "keys-bip39",
    "std",
] }
bitcoin = { version = "0.30.1", default-features = false }
chacha20poly1305 = { version = "0.10.1", default-features = false, features = [
    "alloc",
    "stream",
] }
electrum-client = { version = "0.17.0", default-features = false }
futures = { version = "0.3", default-features = false, features = [
    "executor",
] }
hex = { version = "0.4.3", default-features = false }
rand = { version = "0.8.5", default-features = false }
rgb-lib-migration = { path = "migration", version = "0.2.0" }
reqwest = { version = "0.11", default-features = false, features = [
    "blocking",
    "json",
    "multipart",
    "native-tls",
] }
scrypt = { version = "0.11.0", default-features = false, features = [
    "simple",
    "std",
] }
sea-orm = { version = "=0.12.14", default-features = false, features = [
    "macros",
    "runtime-async-std-native-tls",
    "sqlx-sqlite",
] }
sea-query = { version = "=0.30.7", default-features = false }
serde = { version = "^1.0", default-features = false, features = [
    "derive",
] }
serde_json = { version = "^1.0", default-features = false, features = [
    "preserve_order",
] }
slog = { version = "2.7.0", default-features = false }
slog-async = { version = "2.8.0", default-features = false }
slog-term = { version = "2.9.0", default-features = false }
tempfile = { version = "3.10.1", default-features = false }
thiserror = { version = "1.0", default-features = false }
time = { version = "0.3.28", default-features = false }
tree_magic = { version = "0.2.3", default-features = false }
typenum = { version = "1.17.0", default-features = false }
walkdir = { version = "2.4.0", default-features = false }
zip = { version = "0.6.6", default-features = false, features = [
    "zstd",
] }

# RGB-related deps
amplify = { version = "=4.5.0", default-features = false }
amplify_num = { version = "=0.5.1", default-features = false }  # temporary dependency pin
bp-core = { version = "=0.10.11", default-features = false }
commit_verify = { version = "=0.10.6", default-features = false }
rgb-contracts = { version = "=0.10.2", default-features = false, features = [
    "electrum",
] }
rgb-schemata = { version = "=0.10.1", default-features = false }
rgb-std = { version = "=0.10.9", default-features = false }
rgb-wallet = { version = "=0.10.9", default-features = false }
rgb_core = { package = "rgb-core", version = "=0.10.8", default-features = false }
strict_encoding = { version = "=2.6.2", default-features = false }
strict_types = { version = "=1.6.3", default-features = false }

[dev-dependencies]
copy_dir = { version = "0.1.3", default-features = false }
dircmp = { version = "0.2.0", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
once_cell = { version = "1.18.0", default-features = false }
regex = { version = "1.9.5", default-features = false }
serial_test = { version = "2.0.0", default-features = false }
tempfile = { version = "3.8", default-features = false }
